"use client";

import Link from "next/link";
import { Activity, ArrowUpRight, Cpu, Gauge, Radar, Thermometer } from "lucide-react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const series = [34, 38, 35, 43, 47, 44, 52, 49, 57, 60, 58, 68, 73, 70, 79, 76, 84, 81, 88, 86, 92, 89, 95, 93];
const regions = [
  { label: "Northern", health: 98.6, risk: "Low", tone: "cyan" },
  { label: "Western", health: 91.2, risk: "Elevated", tone: "amber" },
  { label: "Southern", health: 97.8, risk: "Low", tone: "cyan" },
  { label: "Eastern", health: 94.4, risk: "Watch", tone: "blue" },
];

export default function AnalyticsPage() {
  return <><Navbar /><main className="min-h-screen pt-[76px]">
    <section className="border-b border-gs-border"><div className="container-official py-10 sm:py-14">
      <p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-gs-cyan-400">Intelligence layer / analytics</p>
      <div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="gs-display text-5xl uppercase leading-[.86] text-gs-text-primary sm:text-6xl">Grid performance,<br />in motion.</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-gs-text-secondary sm:text-base">A live operational lens for load movement, resilience and emerging risk across the connected grid.</p></div><Link href="/map-explorer" className="gs-nav-cta w-fit">Open live topology <ArrowUpRight className="h-4 w-4" /></Link></div>
    </div></section>
    <div className="container-official space-y-5 py-6 sm:py-8">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={<Gauge />} label="Grid health" value="98.7%" delta="+0.3% since 06:00" /><Metric icon={<Activity />} label="System load" value="68.5%" delta="12.4 GW active demand" /><Metric icon={<Radar />} label="Cascade exposure" value="17%" delta="Within operating threshold" tone="amber" /><Metric icon={<Cpu />} label="Model confidence" value="94.2%" delta="Graph inference stable" /></div>
      <div className="grid gap-5 xl:grid-cols-[1.55fr_.8fr]">
        <section className="gs-analytics-panel overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-gs-border px-5 py-4"><div><p className="gs-data-label">National load profile</p><h2 className="mt-1 text-xl font-semibold text-gs-text-primary">Demand trajectory</h2></div><div className="flex rounded-lg border border-gs-border bg-gs-bg-primary p-1 font-mono text-[10px]"><button className="rounded-md bg-gs-cyan-500 px-3 py-1.5 font-bold text-gs-bg-primary">24H</button><button className="px-3 py-1.5 text-gs-text-secondary">7D</button><button className="px-3 py-1.5 text-gs-text-secondary">30D</button></div></div><div className="p-5"><SignalChart /><div className="mt-3 flex items-center justify-between font-mono text-[10px] text-gs-text-muted"><span>00:00 IST</span><span>12:00 IST</span><span>NOW 18:42</span></div></div></section>
        <section className="gs-analytics-panel p-5"><div className="flex items-center justify-between"><div><p className="gs-data-label">AI signal</p><h2 className="mt-1 text-xl font-semibold text-gs-text-primary">Risk radar</h2></div><span className="grid h-9 w-9 place-items-center rounded-lg border border-gs-border bg-gs-bg-primary text-gs-cyan-400"><Radar className="h-4 w-4" /></span></div><div className="gs-radar my-5"><span className="gs-radar-core">17<small>%</small></span><i /><b /><em /></div><div className="space-y-3 border-t border-gs-border pt-4"><SignalLine label="Thermal stress" value="24" /><SignalLine label="Voltage margin" value="81" /><SignalLine label="Topology strain" value="31" /></div></section>
      </div>
      <div className="grid gap-5 xl:grid-cols-[1.15fr_1fr]">
        <section className="gs-analytics-panel"><div className="flex items-center justify-between border-b border-gs-border px-5 py-4"><div><p className="gs-data-label">Regional signal table</p><h2 className="mt-1 text-xl font-semibold text-gs-text-primary">Grid condition</h2></div><Link href="/operations" className="text-xs font-semibold text-gs-cyan-400 hover:text-gs-cyan-300">Command center</Link></div><div className="divide-y divide-gs-border">{regions.map((region) => <div key={region.label} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 px-5 py-4"><div><p className="font-semibold text-gs-text-primary">{region.label} Region</p><p className="mt-1 font-mono text-[10px] uppercase tracking-wider text-gs-text-muted">Telemetry synchronized</p></div><div className="text-right"><p className="font-mono text-sm font-bold text-gs-text-primary">{region.health}%</p><p className="text-[10px] uppercase tracking-wider text-gs-text-muted">Health</p></div><span className={`gs-risk-badge gs-risk-${region.tone}`}>{region.risk}</span></div>)}</div></section>
        <section className="gs-analytics-panel p-5"><div className="flex items-start justify-between"><div><p className="gs-data-label">Thermal telemetry</p><h2 className="mt-1 text-xl font-semibold text-gs-text-primary">Transformer T17</h2></div><Thermometer className="h-5 w-5 text-gs-amber-500" /></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-lg border border-gs-border bg-gs-bg-primary p-4"><p className="gs-data-label">Live temperature</p><p className="mt-2 font-mono text-3xl font-bold text-gs-text-primary">52.8<span className="text-base text-gs-text-secondary">°C</span></p></div><div className="rounded-lg border border-gs-border bg-gs-bg-primary p-4"><p className="gs-data-label">Limit buffer</p><p className="mt-2 font-mono text-3xl font-bold text-gs-cyan-400">18.2<span className="text-base">°</span></p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-gs-bg-primary"><div className="h-full w-[62%] rounded-full bg-gradient-to-r from-gs-cyan-500 to-gs-blue-500" /></div><p className="mt-3 text-xs leading-relaxed text-gs-text-secondary">Stable under present load. Monitor during the 20:00 peak forecast.</p></section>
      </div>
    </div>
  </main><Footer /></>;
}

function Metric({ icon, label, value, delta, tone = "cyan" }: { icon: React.ReactNode; label: string; value: string; delta: string; tone?: "cyan" | "amber" }) { return <section className="gs-analytics-panel p-5"><div className="flex items-start justify-between"><p className="gs-data-label">{label}</p><span className={tone === "amber" ? "text-gs-amber-500" : "text-gs-cyan-400"}>{icon}</span></div><p className="mt-4 font-mono text-3xl font-bold tracking-[-.06em] text-gs-text-primary">{value}</p><p className="mt-2 text-xs text-gs-text-secondary">{delta}</p></section>; }
function SignalLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between"><span className="text-xs text-gs-text-secondary">{label}</span><span className="font-mono text-xs font-bold text-gs-text-primary">{value}%</span></div>; }
function SignalChart() { const points = series.map((value, index) => `${(index / (series.length - 1)) * 100},${100 - value}`).join(" "); return <div className="relative h-64 overflow-hidden rounded-lg border border-gs-border bg-gs-bg-primary p-3"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(125,211,252,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(125,211,252,.1) 1px,transparent 1px)", backgroundSize: "100% 25%, 16.666% 100%" }} /><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="relative h-full w-full overflow-visible" aria-label="Rising grid demand over 24 hours"><defs><linearGradient id="gridFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#22D3EE" stopOpacity=".28" /><stop offset="100%" stopColor="#22D3EE" stopOpacity="0" /></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#gridFill)" /><polyline points={points} fill="none" stroke="#22D3EE" strokeWidth="1.35" vectorEffect="non-scaling-stroke" /><circle cx="100" cy="7" r="2" fill="#7DD3FC" /></svg><div className="absolute right-4 top-4 rounded bg-gs-bg-secondary/90 px-2 py-1 font-mono text-[10px] font-bold text-gs-cyan-300">12.4 GW</div></div>; }
